# language target
language: c
compiler: gcc
os: linux
dist: trusty
sudo: required

matrix:
  include:
    - env:
      - TARGET_ARCH=x86_64
      - TARGET_DEB_ARCH=amd64
    - env:
        - TARGET_ARCH=aarch64
        - TARGET_DEB_ARCH=arm64
install:
  - 'if [ "$(dpkg-architecture -q DEB_HOST_GNU_CPU)" != "$TARGET_ARCH" ]; then
      echo "deb http://ports.ubuntu.com/ubuntu-ports trusty main restricted multiverse universe" | sudo tee /etc/apt/sources.list.d/ubuntu-ports.list
      sudo dpkg --add-architecture $TARGET_DEB_ARCH;
      sudo apt-get update -y;
      sudo apt-get install -y gcc-multilib crossbuild-essential-$TARGET_DEB_ARCH;
    fi'

script:
  - cmake . -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="cmake/${TARGET_ARCH}-toolchain.cmake"
  - make -j$(nproc)

# make the AppImage bundle
after_success:
  # listing the result
  - ls -lh src/*.so
  # get the tag version

  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh src/libappimage_exec_wrapper.so

branches:
  except:
    # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous.*)$/
