# language target
language: c
compiler: gcc
os: linux
dist: trusty

matrix:
  include:
    - env:
      - TARGET_ARCH=x86_64
    - env:
        - TARGET_ARCH=aarch64
      addons:
        apt:
          update: true
          packages:
            - crossbuild-essential-arm64
script:
  - cmake . -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="cmake/${TARGET_ARCH}-toolchain.cmake"
  - make -j$(nproc)

# make the AppImage bundle
after_success:
  # listing the result
  - ls -lh src/*.so
  # get the tag version

  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh src/libappimage_exec_wrapper.so

branches:
  except:
    # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous.*)$/
