# language target
language: c
compiler: gcc
os: linux
dist: trusty
sudo: required

matrix:
  include:
    - env:
      - TARGET_ARCH=x86_64
      - TARGET_DEB_ARCH=amd64
    - env:
        - TARGET_ARCH=aarch64
        - TARGET_DEB_ARCH=arm64
install:
  - 'if [ "$(uname -m)" != "$TARGET_ARCH" ]; then
      echo "foreign-architecture $TARGET_DEB_ARCH" | sudo tee /etc/dpkg/dpkg.cfg.d/multiarch;
      sudo rm /etc/apt/sources.list /etc/apt/sources.list.d/*
      echo "deb [arch=$TARGET_DEB_ARCH] http://ports.ubuntu.com/ubuntu-ports trusty main restricted multiverse universe" | sudo tee /etc/apt/sources.list;
      echo "deb [arch=$TARGET_DEB_ARCH] http://ports.ubuntu.com/ubuntu-ports trusty-updates main restricted multiverse universe" | sudo tee /etc/apt/sources.list;
      echo "deb [arch=$TARGET_DEB_ARCH] http://ports.ubuntu.com/ubuntu-ports trusty-security main restricted multiverse universe" | sudo tee /etc/apt/sources.list;
      sudo apt-get update -y;
      sudo apt-get install -y gcc-multilib crossbuild-essential-$TARGET_DEB_ARCH pkg-config-$TARGET_ARCH-linux-gnu;
    fi'

script:
  - cmake . -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="cmake/${TARGET_ARCH}-toolchain.cmake"
  - make -j$(nproc)

# make the AppImage bundle
after_success:
  # listing the result
  - ls -lh src/*.so
  # get the tag version

  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - mv src/libappimage_exec_wrapper.so libappimage_exec_wrapper-$TARGET_ARCH.so
  - bash upload.sh libappimage_exec_wrapper-$TARGET_ARCH.so

branches:
  except:
    # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous.*)$/
