name: "build"

on:
  push:
    branches-ignore:
      - master
    tags-ignore:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        TARGET_ARCH: [ x86_64 ]
        BUILD_TYPE: [ Release ]
    env:
      BUILD_TYPE: ${{ matrix.BUILD_TYPE }}
      TARGET_ARCH: ${{ matrix.TARGET_ARCH }}

    steps:
      - uses: actions/checkout@v2

      - name: Build ${{ matrix.BUILD_TYPE }} ${{ matrix.TARGET_ARCH }}
        run: tooling/build-in-docker.sh ${{ env.BUILD_TYPE }}

      - name: Test ${{ matrix.BUILD_TYPE }} ${{ matrix.TARGET_ARCH }}
        if: ${{ env.TARGET_ARCH == 'x86_64' }}
        run: tooling/test-in-docker.sh ${{ env.BUILD_TYPE }}

      - name: Prepare artifacts
        shell: bash
        working-directory: cmake-build-${{ env.BUILD_TYPE }}-${{ env.TARGET_ARCH }}
        run: |
          mkdir -p ../dist
          cp src/apprun/AppRun ../dist/AppRun-$BUILD_TYPE-$TARGET_ARCH
          cp src/hooks/libapprun_hooks.so ../dist/libapprun_hooks-$BUILD_TYPE-$TARGET_ARCH.so

      - name: Upload Artifacts ${{ env.TARGET_ARCH }}
        uses: actions/upload-artifact@v2.1.4
        with:
          name: artifacts
          path: ./dist/*