name: "build"

on:
  push:
    branches-ignore:
      - master
    tags-ignore:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        TARGET_ARCH: [ x86_64 ]
        BUILD_TYPE: [ Release ]
    env:
      BUILD_TYPE: ${{ matrix.BUILD_TYPE }}
      TARGET_ARCH: ${{ matrix.TARGET_ARCH }}

    steps:
      - uses: actions/checkout@v2

      - name: Build
        uses: ./.github/actions/build-x86_64-in-docker
        with:
          build_type: ${{ env.BUILD_TYPE }}

      - name: Check result
        run: ls -la